language: node_js
node_js:
  - 14.2.0
cache: yarn  

dist: xenial

install: 
  - yarn install

script:
  - yarn run test
  
  
deploy:
  provider: s3
  access_key_id: "AKIAZVB6FX5QKHXNXHHF"
  secret_access_key: "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"
  bucket: "S3 bucket"
  cleanup: true
  