language: ruby
node_js:
  - 2.7.1


install: 
  - gem install jekyll

script:
  - jekyll build
  
  
deploy:
  on:
    branch: master
  provider: s3
  bucket: www.blogread.co.uk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-west-2
  acl: public_read
  cleanup: true
  local_dir: ./_site
  