language: ruby
rvm:
  - 2.7.1
cache: yarn
dist: xenial

install: 
  - yarn install

script:
  - yarn run test
  
  
deploy:
  on:
    branch: master
  provider: s3
  bucket: www.blogread.co.uk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-west-2
  acl: public_read
  cleanup: true
  local_dir: ./_site
  